#!/bin/bash

IMAGE=$1


if [ "$#" -ne 1 ]; then
    echo "usage: $0 image"
    exit 1
fi

if [ -z "$REGISSHTRY_REMOTE" ]; then
  echo "\$REGISSHTRY_REMOTE not set";
  exit 1
fi

if [ -z "$REGISSHTRY_PATH" ]; then
  echo "\$REGISSHTRY_PATH not set";
  exit 1
fi

echo "Push image: " $IMAGE && \
docker save $IMAGE| ssh $REGISSHTRY_REMOTE regisshtry-receive ${REGISSHTRY_PATH}/${IMAGE} && \
echo "Successful"
